version: '3.3'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data:/data
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/users.db

  frontend:
    build: ./frontend11
    ports:
      - "3000:80"
    depends_on:
      - backend